### PR TITLE
Create blank Android gradle app

### PR DESCRIPTION
**Pull request by danielpassos**
See: [RHMAP-2063](https://issues.jboss.org/browse/RHMAP-2063)

### CODE REVIEW

**Comment by danielpassos** [comment]
@secondsun Could you review/test that?

**Comment by secondsun** [comment]
See : https://github.com/danielpassos/blank-android-gradle/pull/1

**Comment by secondsun** [comment]
Also, should we use a better launcher icon?

**Comment by danielpassos** [comment]
@secondsun I totally forgot to add the icon :/

**Comment by danielpassos** [comment]
Done!

**Comment by secondsun** [comment]
+1

**Pull request merged**
