### PR TITLE
RHMAP-10275 - Add to ignore idea files created by Android Studio

### PR DESCRIPTION
**Pull request by camilamacedo86**
In this file I added the default .gitignore that we can find in the GitHub ( https://github.com/github/gitignore )

The values that are not in default but were present here before the change were maintained. They are below #RedHat Mobile.

### CODE REVIEW

**Comment by secondsun** [comment]
What files were being included that we needed to .gitignore?  This seems like a lot of unnecessary changes.  (IE things like including apks instead of just ignoring the build directory itself).

**Comment by camilamacedo86** [comment]
In my view, the better we would be adopting this standard on all projects.
This is the pattern you will find on GitHub with a few things added in our case specific.

After all the templates are based so that users can continue, so we can not allow users to rise to the repository undue files.

**Comment by camilamacedo86** [comment]
Also, I believe it would be interesting to start adopting development standards for templates. Such as large default settings, grunt, grandle, .gitignore files for example.

**Comment by secondsun** [comment]
I agree our existing gitignore can be better, but this file is VERY verbose and has lots of very specific rules.  We should be better off making sure that we expose the principles of our .gitignores inside of them than having lots of small details that are easy to over look.

IE make it clear that what we want to do is ignore IDE trash and build artifacts.  Ignoring APKs then the intermediate apk, and then the gradle build directory all in separate sections of the gitignore file obfuscates this.

**Comment by camilamacedo86** [comment]
Could you check it (https://github.com/github/gitignore) ?

This is the GitHub templates for all languages. Normally, the projects adopt these files as standard. 
Also, we can in just use : https://www.npmjs.com/package/generate-gitignore. It will be the same . 

This is the standard with comments. This pattern is within the format setting.
https://git-scm.com/docs/gitignore

In my view we should adopt this standard.

Reasons:

-> It is the standard using in most projects;
-> It is well defined and ensures the most common scenarios, such as logs, files generated by the IDE, etc ..
-> The comments made clear that refers to each item;
-> Today we have each project with a different file which allows the user template rise undue files for the project;
-> Do not need to set a new standard, adopted only what already exists and is common ;

This is my point of view and my personal opinion. Now feel free to approve or not the pull request. This decision is not up to me.

**Comment by danielpassos** [comment]
Hey @camilamacedo86 I agree in improve our gitignore file but I don't agree in all we have today and also all the [github/gitignore](https://github.com/github/gitignore) has.

For example 
1. Could be important to have the keystore in the repo for some reason
2. I'd like to have `.idea` instead of have `.idea/somefiles` 
3. I don't agree with .DS_Store. IMO it can be in the dev global gitignore.

**Comment by camilamacedo86** [comment]
@danielpassos 

About your comment, below are mine considerations and comments:

-- Could be important to have the keystore in the repo for some reason:

The keystore is private key for each application. So for this reason we shouldn't have it in templates. Other reason for don't put it in repo is for security. 
"Maintaining the security of your private key is of critical importance, both to you and to the user."
You can read more in : https://developer.android.com/studio/publish/app-signing.html

-- I'd like to have .idea instead of have .idea/somefiles

You never should save the .idea because it is generated automatically by your local IDE. So, first it is a something always will be generated like build files. For second, it is specific about your development environment and if you save it can be a problem when other person try run it in other place. For this reasons, it is not recommended . 

-- I don't agree with .DS_Store. IMO it can be in the dev global gitignore.

About it I agree with you. It no make sense for me . However, it was there before. 
Important : 
Modification :  I only applied the default configuration + the things that was there before. 
The things that was before in this case are below # Red Hat Mobile  

Observation : I did it only in the templates that I was running locally and they are allowing save not recommended files in the repo.

**Comment by danielpassos** [comment]
@camilamacedo86 

## .idea

I think you did not understood about the `.idea` I'd like to have `.idea` the **whole** directory in .gitignore not only some files like in your PR and in [github/gitignore](https://github.com/github/gitignore/blob/master/Android.gitignore#L37-L38) suggestion

## keystore

I know how much important the Keystore is and already have read this link several times in the last years working with Android. I have missed one of my keystore files and I could not update an app in the play store any more. Anyway, woking in a project with a distributed time IMO have it commited is best thing to do. 

I think the team/customer should decide it theyself and we should not force it.

**Comment by danielpassos** [comment]
We are going to create our own `.gitignore` template for our projects not based in the [https://github.com/github/gitignore](github/gitignore)

**Pull request closed without merging**
